name: luukimthu
favicon: null
layout_spectrum: 0.6974676724057645
typography_spectrum: 0.37821283657103777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.21624472341500223
  lightness: 0.7724188496358693
  saturation: 0.7048487230204046
  rhythmicContrast: 0.36924640042707324
purpose: []
