name: luukimthu
favicon: null
layout_spectrum: 0.6476357355713844
typography_spectrum: 0.9536021212115884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5505174505524337
  lightness: 0.8962058816105127
  saturation: 0.537529150955379
  rhythmicContrast: 0.7567255890462548
purpose: []
